[package]
name = "bluepds"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
atrium-api = { git = "https://github.com/DrChat/atrium.git", branch = "repo" }
atrium-crypto = { git = "https://github.com/DrChat/atrium.git", branch = "repo" }
atrium-repo = { git = "https://github.com/DrChat/atrium.git", branch = "repo" }
atrium-xrpc = { git = "https://github.com/DrChat/atrium.git", branch = "repo" }
atrium-xrpc-client = { git = "https://github.com/DrChat/atrium.git", branch = "repo" }

anyhow = "1.0.94"
axum = { version = "0.8.1", features = ["tower-log", "form", "macros", "ws"] }
azure_core = "0.21.0"
azure_identity = "0.21.0"
base64 = "0.22.1"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
clap-verbosity-flag = "3.0.1"
constcat = "0.5.1"
figment = { version = "0.10.19", features = ["toml", "env"] }
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_ipld_dagcbor = { version = "0.6.0", default-features = false, features = ["std"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["json", "runtime-tokio", "sqlite"] }
thiserror = "2.0.7"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["cors", "fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
uuid = { version = "1.11.0", features = ["v4"] }
sha2 = "0.10.8"
base32 = "0.5.1"
argon2 = { version = "0.5.3", features = ["std"] }
futures = "0.3.31"
reqwest = { version = "0.12.12", features = ["json"] }
