# The superuser password. This only works with connections from localhost.
# Comment this out to disable the superuser.
admin_pw = "admin1"
# The public hostname of the PDS.
host_name = "pds.example.com"
# The path to the primary sqlite database.
db = "sqlite://data/sqlite.db"
# The address to listen to for incoming requests.
listen_address = "0.0.0.0:8000"

# File to store private keys.
# Care must be taken to ensure that the contents of this file aren't exposed!
key = "data/default.key"

[firehose]
relays = ["https://bsky.network"]

[repo]
path = "data/repo"

[plc]
path = "data/plc"
update = true # Do not write updates to the global PLC directory.
